name: flutter_weather_app
description: Weather app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  build_runner: ^2.4.6
  anim_search_bar: ^2.0.3
  geocoding: ^2.0.4
  geolocator: ^10.0.1
  dio: ^5.3.2
  freezed_annotation: ^2.2.0
  freezed: ^2.3.2
  state_notifier: ^0.7.2+1
  sqflite: ^2.2.2
  path: ^1.8.2
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.1.3
  riverpod_annotation: ^2.3.0
  riverpod_generator: ^2.2.3
  flutter_typeahead: ^4.8.0
  flutter_svg: ^2.0.5
  flutter_lints: ^2.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  sqflite_common_ffi:
  mockito: ^5.3.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/ic_favourite_empty.svg
    - assets/ic_favourite_filled.svg
    - assets/ic_home_empty.svg
    - assets/ic_home_filled.svg
    - assets/ic_settings_empty.svg
    - assets/ic_settings_filled.svg
    - .env