name: flutter_weather_app
description: Weather app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  anim_search_bar: ^2.0.3
  geocoding: ^2.0.4
  geolocator: ^10.0.1
  http: ^0.13.4

flutter:
  uses-material-design: true