// Mocks generated by Mockito 5.4.3 from annotations
// in flutter_weather_app/test/mock/presentation/viewmodel/home_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i4;
import 'package:flutter_weather_app/domain/models/suggested_cities_model.dart'
    as _i7;
import 'package:flutter_weather_app/domain/models/weather_model.dart' as _i8;
import 'package:flutter_weather_app/domain/models/weather_model_wrapper.dart'
    as _i6;
import 'package:flutter_weather_app/presentation/state/state.dart' as _i2;
import 'package:flutter_weather_app/presentation/viewmodel/home_screen_viewmodel.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:state_notifier/state_notifier.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeState_0<T> extends _i1.SmartFake implements _i2.State<T> {
  _FakeState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomeViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeViewModel extends _i1.Mock implements _i3.HomeViewModel {
  MockHomeViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onError(_i4.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  _i5.Stream<_i2.State<_i6.WeatherModelWrapper>> get stream =>
      (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i2.State<_i6.WeatherModelWrapper>>.empty(),
      ) as _i5.Stream<_i2.State<_i6.WeatherModelWrapper>>);

  @override
  _i2.State<_i6.WeatherModelWrapper> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeState_0<_i6.WeatherModelWrapper>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.State<_i6.WeatherModelWrapper>);

  @override
  set state(_i2.State<_i6.WeatherModelWrapper>? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.State<_i6.WeatherModelWrapper> get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeState_0<_i6.WeatherModelWrapper>(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i2.State<_i6.WeatherModelWrapper>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> fetchWeatherByCity(
    bool? isCurrent,
    String? city,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchWeatherByCity,
          [
            isCurrent,
            city,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Iterable<_i7.SuggestedCitiesModel>> fetchAutocompleteSearchCity(
          String? suggestedKeyWord) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAutocompleteSearchCity,
          [suggestedKeyWord],
        ),
        returnValue: _i5.Future<Iterable<_i7.SuggestedCitiesModel>>.value(
            <_i7.SuggestedCitiesModel>[]),
      ) as _i5.Future<Iterable<_i7.SuggestedCitiesModel>>);

  @override
  dynamic addFavouriteCity(_i8.WeatherModel? weatherModel) =>
      super.noSuchMethod(Invocation.method(
        #addFavouriteCity,
        [weatherModel],
      ));

  @override
  dynamic deleteFavouriteCity(_i8.WeatherModel? weatherModel) =>
      super.noSuchMethod(Invocation.method(
        #deleteFavouriteCity,
        [weatherModel],
      ));

  @override
  void updateCurrentFavouriteState(bool? isFavourite) => super.noSuchMethod(
        Invocation.method(
          #updateCurrentFavouriteState,
          [isFavourite],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void getFavouriteCities() => super.noSuchMethod(
        Invocation.method(
          #getFavouriteCities,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i2.State<_i6.WeatherModelWrapper>? old,
    _i2.State<_i6.WeatherModelWrapper>? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.RemoveListener addListener(
    _i9.Listener<_i2.State<_i6.WeatherModelWrapper>>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
      ) as _i4.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
