// Mocks generated by Mockito 5.4.3 from annotations
// in flutter_weather_app/test/mock/data/datasource/database/weather_database_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_weather_app/data/datasource/database/weather_database.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WeatherDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherDatabase extends _i1.Mock implements _i2.WeatherDatabase {
  MockWeatherDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<Map<String, dynamic>>> getAllFavouriteCities() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllFavouriteCities,
          [],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<bool> addFavouriteCity(Map<String, dynamic>? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFavouriteCity,
          [city],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteFavouriteCity(Map<String, dynamic>? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFavouriteCity,
          [city],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, dynamic>?> getCityById(String? cityId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCityById,
          [cityId],
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);
}
